name: feature_{{feature_name.snakeCase()}}
description: "This package provides {{feature_name.snakeCase()}} features."
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.3
  flutter: 3.22.2

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  flutter:
    sdk: flutter

dev_dependencies:
  core_testing:
    path: ../../core/testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.1.0

flutter:
