name: core_model
description: This package provides model classes.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.6

dependencies:
  core_common:
    path: ../common
  freezed_annotation: 2.4.1
  riverpod: 2.5.0
  riverpod_annotation: 2.3.4

dev_dependencies:
  build_runner: 2.4.8
  freezed: 2.4.6
  riverpod_generator: 2.3.10
  test: 1.25.2
  yumemi_lints: 1.6.0
